/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Controller.Cpesan;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.text.*;

import javax.swing.*;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;



/**
 *
 * @author Marina Ir
 */
public class Pesan extends javax.swing.JFrame {
Database dbsetting;
String driver,database, user,pass,userlogin;   
   
    public Pesan() {
        initComponents();
dbsetting=new Database();
        driver=dbsetting.SettingPanel("DBDriver");
        database=dbsetting.SettingPanel("DBDatabase");
        user=dbsetting.SettingPanel("DBUsername");
        pass=dbsetting.SettingPanel("DBPassword");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jTextField1 = new javax.swing.JTextField();
        textField1 = new java.awt.TextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        totalnya = new java.awt.Label();
        total = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        batal = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        label28 = new java.awt.Label();
        jLabel11 = new javax.swing.JLabel();
        tfIdOrder = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfDate = new javax.swing.JTextField();
        jcbNoTable = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jOrder1 = new java.awt.Label();
        jum1 = new javax.swing.JTextField();
        hrg1 = new java.awt.Label();
        nasigoreng = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jOrder4 = new java.awt.Label();
        jum4 = new javax.swing.JTextField();
        sateA = new javax.swing.JCheckBox();
        hrg4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jum2 = new javax.swing.JTextField();
        kwetiawg = new javax.swing.JCheckBox();
        hrg2 = new javax.swing.JLabel();
        jOrder2 = new java.awt.Label();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jOrder3 = new java.awt.Label();
        jum3 = new javax.swing.JTextField();
        hrg3 = new javax.swing.JLabel();
        sotoA = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jOrder6 = new java.awt.Label();
        jum6 = new javax.swing.JTextField();
        ejeruk = new javax.swing.JCheckBox();
        hrg6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jOrder5 = new java.awt.Label();
        jum5 = new javax.swing.JTextField();
        eteh = new javax.swing.JCheckBox();
        hrg5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jOrder8 = new java.awt.Label();
        jum8 = new javax.swing.JTextField();
        ekopi = new javax.swing.JCheckBox();
        hrg8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jOrder7 = new java.awt.Label();
        jum7 = new javax.swing.JTextField();
        ecampur = new javax.swing.JCheckBox();
        hrg7 = new javax.swing.JLabel();
        label27 = new java.awt.Label();
        add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("jTextField1");

        textField1.setText("textField1");

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jPanel11.setBackground(new java.awt.Color(204, 255, 204));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Menu", "Harga", "Jumlah Order"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl.setToolTipText("Nama Menu\nHarga\nJumlah Order");
        jScrollPane2.setViewportView(tbl);

        totalnya.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        totalnya.setText("Total");

        jPanel12.setBackground(new java.awt.Color(204, 204, 255));

        batal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        batal.setText("Cancel");

        btnCheckOut.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCheckOut.setText("Check Out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(batal, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(btnCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCheckOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(batal)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        label28.setBackground(new java.awt.Color(204, 204, 255));
        label28.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        label28.setText("          ORDER");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("ID Order");

        tfIdOrder.setEditable(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("No Table");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Date");

        tfDate.setEditable(false);

        jcbNoTable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(totalnya, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83)
                                        .addComponent(jcbNoTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(tfIdOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel18)))
                                .addGap(30, 30, 30)))))
                .addContainerGap())
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(label28, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGap(15, 15, 15)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfIdOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbNoTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalnya, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(label28, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(559, Short.MAX_VALUE)))
        );

        jPanel13.setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/nasi goreng.jpg"))); // NOI18N

        jOrder1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jOrder1.setText("Jumlah Order");

        hrg1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        hrg1.setText("Harga :     25000");

        nasigoreng.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nasigoreng.setText("Nasi Goreng");
        nasigoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nasigorengActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jum1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nasigoreng)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hrg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nasigoreng, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrg1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jum1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        jOrder4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jOrder4.setText("Jumlah Order");

        sateA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sateA.setText("Sate Ayam");
        sateA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sateAActionPerformed(evt);
            }
        });

        hrg4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        hrg4.setText("Harga :  17000");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/satee.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jum4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jOrder4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(sateA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hrg4)
                        .addGap(37, 37, 37))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(sateA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hrg4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jOrder4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jum4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(97, 97, 97))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/kwetiaw.jpg"))); // NOI18N

        kwetiawg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kwetiawg.setText("Kwetiaw Goreng");
        kwetiawg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kwetiawgActionPerformed(evt);
            }
        });

        hrg2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        hrg2.setText("Harga :  15000");

        jOrder2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jOrder2.setText("Jumlah Order");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jum2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(jOrder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(kwetiawg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hrg2)
                        .addGap(74, 74, 74))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kwetiawg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hrg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jOrder2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jum2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/soto.jpg"))); // NOI18N

        jOrder3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jOrder3.setText("Jumlah Order");

        hrg3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        hrg3.setText("Harga :  22000");

        sotoA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sotoA.setText("Soto Ayam");
        sotoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sotoAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jOrder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jum3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(hrg3)
                        .addGap(71, 71, 71))))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(sotoA)
                    .addContainerGap(289, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(hrg3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jOrder3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jum3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(sotoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(212, 212, 212)))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ES JERUK.jpg"))); // NOI18N

        jOrder6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jOrder6.setText("Jumlah Order");

        ejeruk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ejeruk.setText("Es Jeruk");
        ejeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejerukActionPerformed(evt);
            }
        });

        hrg6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        hrg6.setText("Harga :  10000");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jOrder6, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jum6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(ejeruk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hrg6)
                        .addGap(43, 43, 43))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hrg6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ejeruk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jOrder6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jum6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 204));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ES TEH.jpg"))); // NOI18N

        jOrder5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jOrder5.setText("Jumlah Order");

        eteh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eteh.setText("Es Teh");
        eteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etehActionPerformed(evt);
            }
        });

        hrg5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        hrg5.setText("Harga :  10000");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(eteh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hrg5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jOrder5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jum5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eteh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hrg5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jOrder5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jum5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 204));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ES KOPI.jpg"))); // NOI18N

        jOrder8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jOrder8.setText("Jumlah Order");

        ekopi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ekopi.setText("Es Kopi");
        ekopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekopiActionPerformed(evt);
            }
        });

        hrg8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        hrg8.setText("Harga :  12000");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jOrder8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jum8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(ekopi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hrg8)
                        .addGap(64, 64, 64))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ekopi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hrg8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jOrder8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jum8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 204));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ES CAMPUR.jpg"))); // NOI18N

        jOrder7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jOrder7.setText("Jumlah Order");

        ecampur.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ecampur.setText("Es Campur");
        ecampur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecampurActionPerformed(evt);
            }
        });

        hrg7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        hrg7.setText("Harga :  12000");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jOrder7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jum7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(ecampur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hrg7)
                        .addGap(73, 73, 73))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ecampur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hrg7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jOrder7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jum7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(2926, Short.MAX_VALUE))))
        );

        jScrollPane1.setViewportView(jPanel1);

        label27.setBackground(new java.awt.Color(204, 204, 255));
        label27.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        label27.setText("            MENU");

        add.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void simpan1(){
  try{
            Class.forName(driver);
            Connection kon=DriverManager.getConnection(database,user,pass);
            Statement stt=kon.createStatement();
            String SQL="insert into tb_detail values('"+tfIdOrder.getText()+"','"+nasigoreng.getText()+"','"+hrg1.getText()+"','"+jum1.getText()+"')";
           stt.executeUpdate(SQL);
   
           stt.close();
           kon.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        
        }
        }       
public void simpan2(){
  try{
            Class.forName(driver);
            Connection kon=DriverManager.getConnection(database,user,pass);
            Statement stt=kon.createStatement();
            String SQL="insert into tb_pesanan values('"+tfIdOrder.getText()+"','"+tfDate.getText()+"','"+jcbNoTable.getSelectedItem()+"','"+total.getText()+"')";
            
           stt.executeUpdate(SQL);

           stt.close();
           kon.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        
        }
        }  
public void simpan3(){
  try{
            Class.forName(driver);
            Connection kon=DriverManager.getConnection(database,user,pass);
            Statement stt=kon.createStatement();
            String SQL="insert into tb_detail values('"+tfIdOrder.getText()+"','"+kwetiawg.getText()+"','"+hrg2.getText()+"','"+jum2.getText()+"')";
           stt.executeUpdate(SQL);
   
           stt.close();
           kon.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        
        }
        }
public void simpan4(){
  try{
            Class.forName(driver);
            Connection kon=DriverManager.getConnection(database,user,pass);
            Statement stt=kon.createStatement();
            String SQL="insert into tb_detail values('"+tfIdOrder.getText()+"','"+sotoA.getText()+"','"+hrg3.getText()+"','"+jum3.getText()+"')";
           stt.executeUpdate(SQL);
   
           stt.close();
           kon.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        
        }
        }
public void simpan5(){
  try{
            Class.forName(driver);
            Connection kon=DriverManager.getConnection(database,user,pass);
            Statement stt=kon.createStatement();
            String SQL="insert into tb_detail values('"+tfIdOrder.getText()+"','"+sateA.getText()+"','"+hrg4.getText()+"','"+jum4.getText()+"')";
           stt.executeUpdate(SQL);
   
           stt.close();
           kon.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        
        }
        }
public void simpan6(){
  try{
            Class.forName(driver);
            Connection kon=DriverManager.getConnection(database,user,pass);
            Statement stt=kon.createStatement();
            String SQL="insert into tb_detail values('"+tfIdOrder.getText()+"','"+eteh.getText()+"','"+hrg5.getText()+"','"+jum5.getText()+"')";
           stt.executeUpdate(SQL);
   
           stt.close();
           kon.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        
        }
        }
public void simpan7(){
  try{
            Class.forName(driver);
            Connection kon=DriverManager.getConnection(database,user,pass);
            Statement stt=kon.createStatement();
            String SQL="insert into tb_detail values('"+tfIdOrder.getText()+"','"+ejeruk.getText()+"','"+hrg6.getText()+"','"+jum6.getText()+"')";
           stt.executeUpdate(SQL);
   
           stt.close();
           kon.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        
        }
        }
public void simpan8(){
  try{
            Class.forName(driver);
            Connection kon=DriverManager.getConnection(database,user,pass);
            Statement stt=kon.createStatement();
            String SQL="insert into tb_detail values('"+tfIdOrder.getText()+"','"+ecampur.getText()+"','"+hrg7.getText()+"','"+jum7.getText()+"')";
           stt.executeUpdate(SQL);
   
           stt.close();
           kon.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        
        }
        }
public void simpan9(){
  try{
            Class.forName(driver);
            Connection kon=DriverManager.getConnection(database,user,pass);
            Statement stt=kon.createStatement();
            String SQL="insert into tb_detail values('"+tfIdOrder.getText()+"','"+ekopi.getText()+"','"+hrg8.getText()+"','"+jum8.getText()+"')";
           stt.executeUpdate(SQL);
   
           stt.close();
           kon.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        
        }
        }
    private void nasigorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nasigorengActionPerformed
        // TODO add your handling code here:
         if (nasigoreng.isSelected()== true){
           jum1.setEditable(true);
           jum1.requestFocus();
         } else{
           jum1.setEditable(false);
           jum1.setText("");
           nasigoreng.setText("Rp.0,-");
       }
    }//GEN-LAST:event_nasigorengActionPerformed

    private void kwetiawgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kwetiawgActionPerformed
        // TODO add your handling code here:
        if (kwetiawg.isSelected()== true){
           jum2.setEditable(true);
           jum2.requestFocus();
         } else{
           jum2.setEditable(false);
           jum2.setText("");
           kwetiawg.setText("Rp.0,-");
       }
    }//GEN-LAST:event_kwetiawgActionPerformed

    private void sotoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sotoAActionPerformed
        // TODO add your handling code here:
         if (sotoA.isSelected()== true){
           jum3.setEditable(true);
           jum3.requestFocus();
         } else{
           jum3.setEditable(false);
           jum3.setText("");
           sotoA.setText("Rp.0,-");
       }
    }//GEN-LAST:event_sotoAActionPerformed

    private void sateAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sateAActionPerformed
        // TODO add your handling code here:
        if (sateA.isSelected()== true){
           jum4.setEditable(true);
           jum4.requestFocus();
         } else{
           jum4.setEditable(false);
           jum4.setText("");
           sateA.setText("Rp.0,-");
       }
    }//GEN-LAST:event_sateAActionPerformed

    private void etehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etehActionPerformed
        // TODO add your handling code here:
        if (eteh.isSelected()== true){
           jum5.setEditable(true);
           jum5.requestFocus();
         } else{
           jum5.setEditable(false);
           jum5.setText("");
           eteh.setText("Rp.0,-");
       }
    }//GEN-LAST:event_etehActionPerformed

    private void ejerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejerukActionPerformed
        // TODO add your handling code here:
        if (ejeruk.isSelected()== true){
           jum6.setEditable(true);
           jum6.requestFocus();
         } else{
           jum6.setEditable(false);
           jum6.setText("");
           ejeruk.setText("Rp.0,-");
       }
    }//GEN-LAST:event_ejerukActionPerformed

    private void ecampurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecampurActionPerformed
        // TODO add your handling code here:
        if (ecampur.isSelected()== true){
           jum7.setEditable(true);
           jum7.requestFocus();
         } else{
           jum7.setEditable(false);
           jum7.setText("");
           ecampur.setText("Rp.0,-");
       }
    }//GEN-LAST:event_ecampurActionPerformed

    private void ekopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekopiActionPerformed
        // TODO add your handling code here:
        if (ekopi.isSelected()== true){
           jum8.setEditable(true);
           jum8.requestFocus();
         } else{
           jum8.setEditable(false);
           jum8.setText("");
           ekopi.setText("Rp.0,-");
       }
    }//GEN-LAST:event_ekopiActionPerformed
    
    private static void pesan_kosong(){
         JOptionPane.showMessageDialog(null, "Jumlah Order Belum Dimasukkan","Warning", JOptionPane.WARNING_MESSAGE);
    }   
    
    private static void pesan_karakter(){
        JOptionPane.showMessageDialog(null, "Format Jumlah Order Harus Angka","Warning", JOptionPane.WARNING_MESSAGE);
    }
    
    
    
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        int a = 0,b = 0, c=0,d=0,e=0,f=0,g=0,h=0,hrgnasig=0, hrg_kwetiaw=0, hrg_soto=0, 
                hrg_sate=0,hrg_esteh=0,hrg_esjeruk=0,hrg_escampur=0,hrg_eskopi=0, total1;
        if (nasigoreng.isSelected() == false && kwetiawg.isSelected()==false && sotoA.isSelected()==false && sateA.isSelected()==false &&
                eteh.isSelected() == false && ejeruk.isSelected()==false && ecampur.isSelected()==false && ekopi.isSelected()==false){
        JOptionPane.showMessageDialog(null, "Menu Belum Dipesan","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else {
             
        if (nasigoreng.isSelected()==true){
          if (jum1.getText().length()==0){
              pesan_kosong();
              jum1.requestFocus();
              
          }
           else if (jum1.getText().matches("[1-9]")){
              a           = Integer.parseInt(jum1.getText());
              hrgnasig    = 25000;
              total1      = a * hrgnasig;
              total.setText("Rp. "+total1+",-");
              String totall = "Rp" + (total1) +",-";  
              DefaultTableModel model = (DefaultTableModel) tbl.getModel();
              model.addRow(new Object[] {nasigoreng.getText(), hrg1.getText(), jum1.getText()});
              jOrder1.setText("Jumlah Order");
              simpan1();
          } 
        }
        
        if (kwetiawg.isSelected()==true){
          if (jum2.getText().length()==0){
              pesan_kosong();
              jum2.requestFocus();
    }                                   
          else if (jum2.getText().matches("[1-9]")){
              b              = Integer.parseInt(jum2.getText());
              hrg_kwetiaw    = 15000;
              total1         = b * hrg_kwetiaw;
              total.setText("Rp. "+total1+",-");
              String totall = "Rp" + (total1) +",-";     
              DefaultTableModel model = (DefaultTableModel) tbl.getModel();
              model.addRow(new Object[] {kwetiawg.getText(), hrg2.getText(), jum2.getText()});
              jOrder2.setText("Jumlah Order");
              simpan3();
          } 
        }
        
        if (sotoA.isSelected()==true){
          if (jum3.getText().length()==0){
              pesan_kosong();
              jum3.requestFocus();
    }                                   
          else if (jum3.getText().matches("[1-9]")){
              c           = Integer.parseInt(jum3.getText());
              hrg_soto    = 22000;
              total1      = c * hrg_soto;
              total.setText("Rp. "+total1+",-");
              String totall = "Rp" + (total1) +",-";   
              DefaultTableModel model = (DefaultTableModel) tbl.getModel();
              model.addRow(new Object[] {sotoA.getText(), hrg3.getText(), jum3.getText()});
              jOrder3.setText("Jumlah Order");
              simpan4();
          } 
        }
        
        if (sateA.isSelected()==true){
          if (jum4.getText().length()==0){
              pesan_kosong();
              jum4.requestFocus();
    }                                   
          else if (jum4.getText().matches("[1-9]")){
              d           = Integer.parseInt(jum4.getText());
              hrg_sate    = 17000;
              total1      = d * hrg_sate;
              total.setText("Rp. "+total1+",-");
              String totall = "Rp" + (total1) +",-";  
              DefaultTableModel model = (DefaultTableModel) tbl.getModel();
              model.addRow(new Object[] {sateA.getText(), hrg4.getText(), jum4.getText()});
              jOrder4.setText("Jumlah Order");
              simpan5();
          } 
        }
        
         if (eteh.isSelected()==true){
          if (jum5.getText().length()==0){
              pesan_kosong();
              jum5.requestFocus();
    }                                   
          else if (jum5.getText().matches("[1-9]")){
              e            = Integer.parseInt(jum5.getText());
              hrg_esteh    = 10000;
              total1       = e * hrg_esteh;
              total.setText("Rp. "+total1+",-");
              String totall = "Rp" + (total1) +",-"; 
              DefaultTableModel model = (DefaultTableModel) tbl.getModel();
              model.addRow(new Object[] {eteh.getText(), hrg5.getText(), jum5.getText()});
              jOrder5.setText("Jumlah Order");
              simpan6();
          } 
        }
         
         if (ejeruk.isSelected()==true){
          if (jum6.getText().length()==0){
              pesan_kosong();
              jum6.requestFocus();
    }                                   
          else if (jum6.getText().matches("[1-9]")){
              f              = Integer.parseInt(jum6.getText());
              hrg_esjeruk    = 10000;
              total1         = f * hrg_esjeruk;
              total.setText("Rp. "+total1+",-");
              String totall = "Rp" + (total1) +",-";
              DefaultTableModel model = (DefaultTableModel) tbl.getModel();
              model.addRow(new Object[] {ejeruk.getText(), hrg6.getText(), jum6.getText()});
              jOrder6.setText("Jumlah Order");
              simpan7();
          } 
        }
         
         if (ecampur.isSelected()==true){
          if (jum7.getText().length()==0){
              pesan_kosong();
              jum7.requestFocus();
    }                                   
          else if (jum7.getText().matches("[1-9]")){
              g               = Integer.parseInt(jum7.getText());
              hrg_escampur    = 12000;
              total1          = g * hrg_escampur;
              total.setText("Rp. "+total1+",-");
              String totall = "Rp" + (total1) +",-"; 
              DefaultTableModel model = (DefaultTableModel) tbl.getModel();
              model.addRow(new Object[] {ecampur.getText(), hrg7.getText(), jum7.getText()});
              jOrder7.setText("Jumlah Order");
               simpan8();
          } 
        }
         
         if (ekopi.isSelected()==true){
          if (jum8.getText().length()==0){
              pesan_kosong();
              jum8.requestFocus();
    }                                   
          else if (jum8.getText().matches("[1-9]")){
              h             = Integer.parseInt(jum8.getText());
              hrg_eskopi    = 12000;
              total1        = h * hrg_eskopi;
              total.setText("Rp. "+total1+",-");
              String totall = "Rp" + (total1) +",-"; 
              DefaultTableModel model = (DefaultTableModel) tbl.getModel();
              model.addRow(new Object[] {ekopi.getText(), hrg8.getText(), jum8.getText()});
              jOrder8.setText("Jumlah Order");
               simpan9();
          } 
        }
     }
    }//GEN-LAST:event_addActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
        simpan2();
    }//GEN-LAST:event_btnCheckOutActionPerformed
    
    public JButton getbeli() {
        
        int jum = 0;
        return add;
    }
    
    public JButton gettransaksi() {
        
        return btnCheckOut;
       
    }
    
    public JButton getbatal() {
        return batal;
    }
     
    public JTable gettbl()
    {
        return tbl;
        
    }    
    
     public int getSelectedOrder(){
        return tbl.getSelectedRow();
    }
    
    public void setTbl(DefaultTableModel model){
        tbl.setModel(model);
    }
    
    public void reset(){
        nasigoreng.setSelected(false);
        kwetiawg.setSelected(false);
        sateA.setSelected(false);
        sotoA.setSelected(false);
        ejeruk.setSelected(false);
        eteh.setSelected(false);
        ecampur.setSelected(false);
        
    }
    
    public void setJumlahOrder(String s){
        jum1.setText(s);
        jum2.setText(s);
        jum4.setText(s);
        jum3.setText(s);
        jum6.setText(s);
        jum8.setText(s);
        jum7.setText(s);
    }
    
    public void setIdOrder() {
        
    }
    
    public void setDate() {
   Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String s = sdf.format(date);
        tfDate.setText(s);
    }
    
    public int getJumlahOrder(){
        return Integer.parseInt(jum1.getText());
    }
    
    public String getNamaMenu() {
        return nasigoreng.getText();
    }
    
    public String getHarga() {
        return hrg1.getText();
    }
    
    public JButton getBtnCheckOut() {
        return btnCheckOut;
    }
    
    public void addActionListener(ActionListener e) {
        add.addActionListener(e);
        btnCheckOut.addActionListener(e);
    }
    
    public void addMouseAdapter(Cpesan aThis){
        tbl.addMouseListener(aThis);
    }
    
    public void setListMenu (Object[][] data,Object[] a) {
        this.tbl.setModel(new DefaultTableModel(data, a){
        @Override
        public boolean isCellEditable(int row,int column){
            return false;
        }
        });
    
    /**
     * @param args the command line arguments
     */
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton batal;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JCheckBox ecampur;
    private javax.swing.JCheckBox ejeruk;
    private javax.swing.JCheckBox ekopi;
    private javax.swing.JCheckBox eteh;
    private java.awt.Label hrg1;
    private javax.swing.JLabel hrg2;
    private javax.swing.JLabel hrg3;
    private javax.swing.JLabel hrg4;
    private javax.swing.JLabel hrg5;
    private javax.swing.JLabel hrg6;
    private javax.swing.JLabel hrg7;
    private javax.swing.JLabel hrg8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Label jOrder1;
    private java.awt.Label jOrder2;
    private java.awt.Label jOrder3;
    private java.awt.Label jOrder4;
    private java.awt.Label jOrder5;
    private java.awt.Label jOrder6;
    private java.awt.Label jOrder7;
    private java.awt.Label jOrder8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jcbNoTable;
    private javax.swing.JTextField jum1;
    private javax.swing.JTextField jum2;
    private javax.swing.JTextField jum3;
    private javax.swing.JTextField jum4;
    private javax.swing.JTextField jum5;
    private javax.swing.JTextField jum6;
    private javax.swing.JTextField jum7;
    private javax.swing.JTextField jum8;
    private javax.swing.JCheckBox kwetiawg;
    private java.awt.Label label27;
    private java.awt.Label label28;
    private javax.swing.JCheckBox nasigoreng;
    private javax.swing.JCheckBox sateA;
    private javax.swing.JCheckBox sotoA;
    private javax.swing.JTable tbl;
    private java.awt.TextField textField1;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfIdOrder;
    private javax.swing.JLabel total;
    private java.awt.Label totalnya;
    // End of variables declaration//GEN-END:variables

    public void showMessage(String message, String title, int type) {
        JOptionPane.showMessageDialog(null, message, title, type);
    }

    public void setNamaMenu(String namaMenu) {
        
    }

    public void setHarga(int harga) {
        
    }

    public void setJumlahOrder(int jumlahOrder) {
        
    }


  
    
    
}
